# Generated by Django 4.2.14 on 2024-07-13 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BookModel", "0002_book_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="BookModel.publish"
            ),
        ),
    ]
